volumes:
  db_storage:
    name: n8n_db_storage
  n8n_storage:
    name: n8n_data

services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_NON_ROOT_USER=${POSTGRES_NON_ROOT_USER}
      - POSTGRES_NON_ROOT_PASSWORD=${POSTGRES_NON_ROOT_PASSWORD}
      - TZ=${TZ}
    volumes:
      - db_storage:/var/lib/postgresql/data
      - ./init-data.sh:/docker-entrypoint-initdb.d/init-data.sh:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h 127.0.0.1 -U ${POSTGRES_USER} -d ${POSTGRES_DB} || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 20

  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=${POSTGRES_DB}
      - DB_POSTGRESDB_USER=${POSTGRES_NON_ROOT_USER}
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_NON_ROOT_PASSWORD}
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
      - TZ=${TZ}
      - N8N_BASIC_AUTH_ACTIVE=${N8N_BASIC_AUTH_ACTIVE}
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD}
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
      - N8N_HOST=${N8N_HOST}
      - N8N_PORT=${N8N_PORT}
      - N8N_PROTOCOL=${N8N_PROTOCOL}
      - WEBHOOK_URL=${WEBHOOK_URL}
    ports:
      - "5678:5678"
    volumes:
      - n8n_storage:/home/node/.n8n
    depends_on:
      postgres:
        condition: service_healthy
      fetcher:
        condition: service_started

  fetcher:
    build: ./services/fetcher
    container_name: job-fetcher
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - TZ=${TZ:-Australia/Sydney}
      - HOURS_OLD=${HOURS_OLD:-48}
      - RESULTS_WANTED=${RESULTS_WANTED:-120}
      - LINKEDIN_LOCATION=${LINKEDIN_LOCATION:-Sydney, New South Wales, Australia}
      - TITLE_INCLUDE_FROM_QUERIES=${TITLE_INCLUDE_FROM_QUERIES:-1}
      - FILTER_DESCRIPTION=${FILTER_DESCRIPTION:-1}
      - GOOGLE_CREDS_PATH=/app/credentials/credentials.json
    volumes:
      - ./credentials.json:/app/credentials/credentials.json:ro
      - ./services/fetcher/history:/app/history
      - ./templates:/app/templates:ro
      - ./outputs:/app/outputs
    ports:
      - "8000:8000"

  texlive:
    image: texlive/texlive:latest
    container_name: texlive
    volumes:
      - ./:/workspace
    working_dir: /workspace
    entrypoint: tail -f /dev/null
    restart: unless-stopped

networks:
  default:
    name: jobflow
